### PR TITLE
Added ability to use ~/ links in markdown.

### PR DESCRIPTION
**Pull request by JoshClose**

### CODE REVIEW

**Comment by JoshClose** [comment]
Locally on Windows all tests pass.

The error that is happening on the build is this code.

```cs
if (Uri.TryCreate(url, UriKind.Absolute, out Uri _))
{
    throw new InvalidOperationException($"Absolute URL '{url}' cannot be used for a RelativeUrl.");
}
```

for URIs like `/foo`. Why on Linux would it be able to create that as an absolute URI?

**Comment by daveaglick** [comment]
This is awesome, and you're my hero for adding a bunch of unit tests.

> Why on Linux would it be able to create that as an absolute URI?

That does seem strange - URIs are a well-defined standard and should work the same on any platform as far as I know.

The failing test might not be that at all - I've had trouble getting the code that forks processes for the `StartProcess` module to test correctly on non-Windows systems. I know it works but there's something odd about the timing. I might just disable those tests going forward so not to confuse things.

In any case, I'm going to merge this and get a release out while I finish up the longer-term changes with the new module. Great work!

**Comment by JoshClose** [comment]
I found that that only thing that makes a URL absolute is `scheme:` so I changed it to just look for a `:` in the link. I also made `RelativeUrl` generate a URL since `UriBuilder` will always insert a `/` at the front of the path making it impossible to do folder relative URL.

**Comment by daveaglick** [comment]
I'm also working on better support for fragments and query strings so they stop getting encoded using the `LinkGenerator` - going to be a nice set of improvements out of this issue.

**Comment by JoshClose** [comment]
> This is awesome, and you're my hero for adding a bunch of unit tests.

I've found it to be crucial for stuff like this.

> I'm also working on better support for fragments and query strings so they stop getting encoded using the LinkGenerator - going to be a nice set of improvements out of this issue.

Awesome! I'm really liking this framework. The learning curve is kinda large starting fresh, but I've been able to find a way to do everything I've needed in a simple way. I'm migrating my site from React Static and Statiq is quite refreshing.

**Pull request merged**
